### ISSUE TITLE
Add .clang-tidy to the project

### ISSUE THREAD

**Issue by karnkaul** [Rinzii/genesis#20]
While Visual Studio has built-in clang-tidy integration, the clangd extension on VSCode does not trigger any checks without this file being present. 
As a bonus, with the file checked in we can control exactly which checks we want uniformly for all developers.

Example:

```yaml
---
Checks: 'clang-analyzer-*,concurrency-*,cppcoreguidelines-*,misc-*,-misc-non-private-member-variables-in-classes,modernize-*,performance-*,portability-*,readability-*'
...
```

**Comment by Rinzii** [comment]
Agreed, I thought I had already added this but I must of missed it when I first created the project. I'll add one in shortly. ^^
