### ISSUE TITLE
replace std::chrono::high_resolution_clock in time.hpp with std::chrono::steady_clock

### ISSUE THREAD

**Issue by Rinzii** [Rinzii/genesis#32]
Currently our time class is using std::chrono::high_resolution_clock which comes with many different implementation details and is generally an alias for std::chrono::steady_clock or std::chrono::system_clock. 

For better consistency cross platform I think we should instead explicitly use std::chrono::steady_clock with the smallest tick period set manually. This way we can ensure a consistent monotonic cross platform clock that won't have platform or compiler specific details we would have to worry about.

**Comment by Rinzii** [comment]
Hey @Kouros26 would you be able to handle this issue since it relates to the timer class you worked on?

**Comment by Kouros26** [comment]
sure I'll work on it soon

**Comment by Kouros26** [comment]
@Rinzii I've done some research and I didn't find anything about changing a steady_clock's period ? From what I understood this is a constant already defined and you can't manually change it

**Comment by Rinzii** [comment]
> @Rinzii I've done some research and I didn't find anything about changing a steady_clock's period ? From what I understood this is a constant already defined and you can't manually change it

Ah my bad must of misread the docs though not being able to set the period directly does not change the underlying issue stated above. From what I’ve read though the period is up to the implementation details but it appears that generally they choose to use the lowest available.

**Comment by Rinzii** [comment]
> > @Rinzii I've done some research and I didn't find anything about changing a steady_clock's period ? From what I understood this is a constant already defined and you can't manually change it
> 
> Ah my bad must of misread the docs though not being able to set the period directly does not change the underlying issue stated above. From what I’ve read though the period is up to the implementation details but it appears that generally they choose to use the lowest available.

The biggest issue is with the unknown of if we get a system_clock or a steady_clock. The later being what we want since it is specifically meant for measurement between intervals.
