### ISSUE TITLE
Add stream functionality to the logger

### ISSUE THREAD

**Issue by Rinzii** [Rinzii/genesis#44]
Many times I've found I want to compact a lot of information into a single log message instead of multiple using a for loop. One common area I wish for stream functionality is in Vulkan where I have to deal with a vector of items and don't want to make complicated round about means of grouping that information. I'd be nice to be able to do something like:

```
gen::logger::debug logger("vulkan");
logger.start;
for (i = 0; i < 10; i++)
{
logger << "hello world";
}
logger.stop; // flush the stream and send the log message
```
^ This is an example of what the approach could be but honestly it can be anything that makes the most sense.

Allow stream operations would allow to group information together without risking fragmentation of the log messages or extremely complicated lambda functions to group everything together. Along with providing more robust operations.

All of this is of course a nice to have and is not necessarily required, but for sure something worth considering.

**Comment by karnkaul** [comment]
Why not use what's already built-in to the standard library?
```cpp
auto str = std::stringstream{"vulkan"};
for (i = 0; i < 10; i++)
{
  str << "hello world";
}
logger::debug(str.str());
```

Or:
```cpp
auto str = std::string{"vulkan"};
for (i = 0; i < 10; i++)
{
  std::format_to(std::back_inserter(str), "hello world");
}
logger::debug(str);
```

**Comment by Rinzii** [comment]
This is a valid argument to make. I’m personally not the biggest fan of having to bring in external includes as I like everything to come from a single clean package, but I don’t think my opinion on that matter is a strong argument. What do you think @Kouros26 ?
