### ISSUE TITLE
Logger does not output to console when inside of a catch block

### ISSUE THREAD

**Issue by Rinzii** [Rinzii/genesis#60]
While I was working on the rendering pipeline I noticed that inside of the catch block in the main was not outputting anything to the console. After some testing I was able to identify that if std::cout was used I'd output to the console, but if the logger was used nothing would output at all. I've not identified what is causing this issue, but it seems to only happen inside of the catch block of a try catch.

The version of the logger I am using is the same as the main branch.

This is where the issue is arising on my end:

```

#include <game/game.hpp>
#include <gen/logger/instance.hpp>
#include <gen/logger/log.hpp>
#include <gen/util/version.hpp>

// temp
#include "gen/io/fileUtils.hpp"

// TODO: Replace this with a config file. At least for the startup window size.
static constexpr const char * appName{"Genesis Game - Editor"};
static constexpr gen::Version appVersion{0, 0, 1};
static constexpr mim::vec2i startingWindowSize{800, 600};

int main()
{
	try
	{
		auto logger = gen::logger::Instance{}; // Required to initialize the logger

		gen::logger::general.log("Current executable path: {}", gen::io::getExecutablePath().string());
                // ^This outputs to the console

		gen::Game app{appName, appVersion.getVersion(), startingWindowSize};
		app.run();
	}
	catch (std::exception const & e)
	{
		gen::logger::general.error("Exception: {}", e.what());
                // This does not output to console.
		return 1; // Program returns 1 but does not output to console
	}

	return 0;
}
```

SYSTEM INFO:

OS: Arch Linux x86_64
KERNEL: 6.6.1-arch1-1
TOOL CHAIN: GCC 13.2.1
BUILD CONFIG: ninja-nopch
IDE: clion

**Comment by karnkaul** [comment]
This is because the logger instance is inside the try block. Move it outside so it remains alive in catch blocks too.
